# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.21
# 
# >> macros
# << macros

Name:       libiphb
Summary:    API for IP Heartbeat service
Version:    0.61.26.p1.gitec5c50d7
Release:    0
Group:      System/System Control
License:    LGPLv2+
URL:        http://meego.gitorious.org/meego-middleware/libiphb
Source0:    %{name}-%{version}.tar.gz
Source100:  libiphb.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  libdsme-devel


%description
This package contains C API for using IP Heartbeat service.



%package devel
Summary:    Development files for IP Heartbeat service
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains C headers for the IP Heartbeat API.


%package test
Summary:    Test tool for IP Heartbeat service
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description test
Command line utility to test IP Heartbeat functionality.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
unset LD_AS_NEEDED
# >> build pre
chmod a+x autogen.sh
./autogen.sh
chmod a+x configure
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig








%files
%defattr(-,root,root,-)
%{_libdir}/libiphb.so.*
%doc COPYING AUTHORS INSTALL README NEWS ChangeLog
# >> files
# << files


%files devel
%defattr(-,root,root,-)
%attr(644,root,root)%{_includedir}/iphbd/*
%{_libdir}/libiphb.so
%{_libdir}/pkgconfig/libiphb.pc
%doc COPYING
# >> files devel
# << files devel

%files test
%defattr(-,root,root,-)
%{_bindir}/hbtest
%doc COPYING
# >> files test
# << files test

